anketler/urls.py
from django.urls import path

from . import views

app_name = 'anketler'

urlpatterns = [
    path('', views.AnasayfaView.as_view(), name='anasayfa'),
    path('<int:pk>/', views.DetayView.as_view(), name='detay'),
    path('<int:pk>/sonuclar/', views.SonuclarView.as_view(), name='sonuclar'),
    path('<int:soru_id>/oy/', views.oy, name='oy'),
]

sitem/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('anketler/', include('anketler.urls')),
    path('admin/', admin.site.urls),
]

anketler/models.py
import datetime
from django.db import models
from django.utils import timezone


class Soru(models.Model):
    soru_metni = models.CharField(max_length=200)
    yayim_tarihi = models.DateTimeField('yayımlanma tarihi')

    def __str__(self):
        return self.soru_metni

    def yakinda_yayimlanan(self):
        suanki_zaman = timezone.now()
        return suanki_zaman - datetime.timedelta(days=1) <= self.yayim_tarihi <= suanki_zaman
        yakin_zamanda_yayinlanan.admin_order_field = 'yayim_tarihi'
        yakin_zamanda_yayinlanan.boolean = True
        yakin_zamanda_yayinlanan.short_description = 'Yakında yayımlanan?'


class Secim(models.Model):
    soru = models.ForeignKey(Soru, on_delete=models.CASCADE)
    secim_metni = models.CharField(max_length=200)
    oylar = models.IntegerField(default=0)

    def __str__(self):
        return self.secim_metni

anketler/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from .models import Secim, Soru


class AnasayfaView(generic.ListView):
    template_name = 'anketler/anasayfa.html'
    context_object_name = 'son_sorular_listesi'

    def get_queryset(self):
        # Henüz yayınlanmamış sorular hariç.
        return Soru.objects.filter(yayim_tarihi__lte=timezone.now())


class DetayView(generic.DetailView):
    model = Soru
    template_name = 'anketler/detay.html'


class SonuclarView(generic.DetailView):
    model = Soru
    template_name = 'anketler/sonuclar.html'


def oy(request, soru_id):
    soru = get_object_or_404(Soru, pk=soru_id)
    try:
        secim_secildi = soru.secim_set.get(pk=request.POST['secim'])
    except (KeyError, Secim.DoesNotExist):
        # Soruyu oylama biçiminin yeniden görüntünlemesi.
        return render(request, 'anketler/detay.html', {
            'soru': soru,
            'hata_mesaji': "Herhangi bir seçim yapmadınız.",
        })
    else:
        secim_secildi.oylar += 1
        secim_secildi.save()
        '''POST verileri her zaman bir HttpResponseRedirect döndürür.
		Bu, bir kullanıcı "geri" düğmesine basarsa
		verilerin iki kez gönderilmesini önler.'''
        return HttpResponseRedirect(reverse('anketler:sonuclar', args=(soru.id,)))

anketler/templates/anketler/anasayfa.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'anketler/style.css' %}">

{% if son_sorular_listesi %}
    <ul>
    {% for soru in son_sorular_listesi %}
    	<li><a href="/anketler/{{ soru.id }}/">{{ soru.soru_metni }}</a></li>
    {% endfor %}
    </ul>
{% else %}
	<p>Anket bulunamadı.</p>
{% endif %}

anketler/templates/anketler/detay.html
<h1>{{ soru.soru_metni 	}}</h1>

{% if hata_mesaji %}<p><strong>{{ hata_mesaji }}</strong></p>{% endif %}

<form action="{% url 'anketler:oy' soru.id %}" method="post">
{% csrf_token %}
{% for secim in soru.secim_set.all %}
	<input type="radio" name="secim" id="secim{{ forloop.counter }}" value="{{ secim.id }}"/>
	<label for="secim {{ forloop.counter }}">{{ secim.secim_metni }}</label><br/>
{% endfor %}
<input type="submit" value="Oy ver"/>
</form>

anketler/templates/anketler/sonuclar.html
<h1>{{ soru.soru_metni }}</h1>

<ul>
{% for secim in soru.secim_set.all %}
	<li>{{ secim.secim_metni }} -- {{ secim.oylar }} oy{{ secim.oylar|pluralize }}</li>
{% endfor %}
</ul>